import { Ingredient } from "./types";

export const ingredients: Ingredient[] = [
  { id: "1", name: "Potato", category: "Veggies", image: "/ingredients/potato.webp" },
  { id: "2", name: "Carrot", category: "Veggies", image: "/ingredients/carrot.webp" },
  {
    id: "3",
    name: "Soy Sauce",
    category: "Condiments",
    image: "/ingredients/soy-sauce.webp",
  },
  {
    id: "4",
    name: "Sweet Potato",
    category: "Veggies",
    image: "/ingredients/sweet-potato.webp",
  },
  { id: "5", name: "Grapes", category: "Fruits", image: "/ingredients/grapes.webp" },
  { id: "6", name: "Celery", category: "Veggies", image: "/ingredients/cellery.webp" },
  { id: "7", name: "Limes", category: "Fruits", image: "/ingredients/limes.webp" },
  { id: "8", name: "Ginger", category: "Spices", image: "/ingredients/ginger.webp" },
  {
    id: "10",
    name: "Red Onion",
    category: "Veggies",
    image: "/ingredients/red-onion.webp",
  },
  { id: "11", name: "Bananas", category: "Fruits", image: "/ingredients/banana.webp" },
  {
    id: "12",
    name: "Strawberries",
    category: "Fruits",
    image: "/ingredients/strawberries.webp",
  },
  { id: "13", name: "Rice", category: "Grains", image: "/ingredients/rice.webp" },
  {
    id: "14",
    name: "Chili Crisp",
    category: "Condiments",
    image: "/ingredients/chili-crisp.webp",
  },
  {
    id: "15",
    name: "Golden Curry",
    category: "Condiments",
    image: "/ingredients/golden-curry.webp",
  },
  { id: "16", name: "Ají Limo", category: "Spices", image: "/ingredients/aji-limo.webp" },
  { id: "17", name: "Ají Panca", category: "Spices", image: "/ingredients/aji-panca.webp" },
  { id: "18", name: "Garlic", category: "Veggies", image: "/ingredients/garlic.webp" },
  { id: "19", name: "Short Ribs", category: "Protein", image: "/ingredients/short-ribs.webp" },
  { id: "20", name: "Cilantro", category: "Spices", image: "/ingredients/cilantro.webp" },
  { id: "21", name: "Squash", category: "Veggies", image: "/ingredients/squash.webp" },
  { id: "22", name: "Beer", category: "Condiments", image: "/ingredients/beer.webp" },
  { id: "23", name: "Whole Chicken", category: "Protein", image: "/ingredients/whole-chicken.webp" },
  { id: "24", name: "Mustard", category: "Condiments", image: "/ingredients/mustard.webp" },
  { id: "25", name: "Parsley", category: "Spices", image: "/ingredients/parsley.webp" },
  { id: "26", name: "Red Wine Vinegar", category: "Condiments", image: "/ingredients/red-wine-vinegar.webp" },
];

export const categories = [
  "All",
  "Fruits",
  "Veggies",
  "Protein",
  "Grains",
  "Dairy",
  "Oils",
  "Condiments",
  "Spices",
];
