import { Ingredient } from "./types";

export const ingredients: Ingredient[] = [
  { id: "16", name: "Ají Limo", category: "Spices", image: "/ingredients/aji-limo.webp" },
  { id: "17", name: "Ají Panca", category: "Spices", image: "/ingredients/aji-panca.webp" },
  { id: "27", name: "Avocado", category: "Fruits", image: "/ingredients/avocado.webp" },
  { id: "11", name: "Bananas", category: "Fruits", image: "/ingredients/banana.webp" },
  { id: "22", name: "Beer", category: "Condiments", image: "/ingredients/beer.webp" },
  { id: "28", name: "Bell Pepper", category: "Veggies", image: "/ingredients/bell-pepper.webp" },
  { id: "2", name: "Carrot", category: "Veggies", image: "/ingredients/carrot.webp" },
  { id: "6", name: "Celery", category: "Veggies", image: "/ingredients/cellery.webp" },
  { id: "29", name: "Chicken Breast", category: "Protein", image: "/ingredients/chicken-breast.webp" },
  { id: "14", name: "Chili Crisp", category: "Condiments", image: "/ingredients/chili-crisp.webp" },
  { id: "20", name: "Cilantro", category: "Spices", image: "/ingredients/cilantro.webp" },
  { id: "30", name: "Eggs", category: "Protein", image: "/ingredients/eggs.webp" },
  { id: "18", name: "Garlic", category: "Veggies", image: "/ingredients/garlic.webp" },
  { id: "8", name: "Ginger", category: "Spices", image: "/ingredients/ginger.webp" },
  { id: "15", name: "Golden Curry", category: "Condiments", image: "/ingredients/golden-curry.webp" },
  { id: "5", name: "Grapes", category: "Fruits", image: "/ingredients/grapes.webp" },
  { id: "31", name: "Green Apple", category: "Fruits", image: "/ingredients/green-apple.webp" },
  { id: "32", name: "Lettuce", category: "Veggies", image: "/ingredients/lettuce.webp" },
  { id: "7", name: "Limes", category: "Fruits", image: "/ingredients/limes.webp" },
  { id: "33", name: "Mayo", category: "Condiments", image: "/ingredients/mayo.webp" },
  { id: "24", name: "Mustard", category: "Condiments", image: "/ingredients/mustard.webp" },
  { id: "34", name: "Oil", category: "Oils", image: "/ingredients/oil.webp" },
  { id: "35", name: "Oyster Sauce", category: "Condiments", image: "/ingredients/oyster-sauce.webp" },
  { id: "25", name: "Parsley", category: "Spices", image: "/ingredients/parsley.webp" },
  { id: "36", name: "Pineapple", category: "Fruits", image: "/ingredients/pineapple.webp" },
  { id: "1", name: "Potato", category: "Veggies", image: "/ingredients/potato.webp" },
  { id: "37", name: "Red Apple", category: "Fruits", image: "/ingredients/red-apple.webp" },
  { id: "10", name: "Red Onion", category: "Veggies", image: "/ingredients/red-onion.webp" },
  { id: "26", name: "Red Wine Vinegar", category: "Condiments", image: "/ingredients/red-wine-vinegar.webp" },
  { id: "13", name: "Rice", category: "Grains", image: "/ingredients/rice.webp" },
  { id: "19", name: "Short Ribs", category: "Protein", image: "/ingredients/short-ribs.webp" },
  { id: "3", name: "Soy Sauce", category: "Condiments", image: "/ingredients/soy-sauce.webp" },
  { id: "21", name: "Squash", category: "Veggies", image: "/ingredients/squash.webp" },
  { id: "38", name: "Sriracha Sauce", category: "Condiments", image: "/ingredients/sriracha-sauce.webp" },
  { id: "12", name: "Strawberries", category: "Fruits", image: "/ingredients/strawberries.webp" },
  { id: "4", name: "Sweet Potato", category: "Veggies", image: "/ingredients/sweet-potato.webp" },
  { id: "39", name: "Tomato", category: "Veggies", image: "/ingredients/tomato.webp" },
  { id: "40", name: "White Vinegar", category: "Condiments", image: "/ingredients/white-vinegar.webp" },
  { id: "23", name: "Whole Chicken", category: "Protein", image: "/ingredients/whole-chicken.webp" },
  { id: "41", name: "Yellow Onion", category: "Veggies", image: "/ingredients/yellow-onion.webp" },
];

export const categories = [
  "All",
  "Fruits",
  "Veggies",
  "Protein",
  "Grains",
  "Dairy",
  "Oils",
  "Condiments",
  "Spices",
];
