import { Ingredient } from "./types";

export const ingredients: Ingredient[] = [
  { id: "59", name: "Ají Amarillo", category: "Aromatics", image: "/ingredients/aji-amarillo.webp" },
  { id: "16", name: "Ají Limo", category: "Aromatics", image: "/ingredients/aji-limo.webp" },
  { id: "17", name: "Ají Panca", category: "Aromatics", image: "/ingredients/aji-panca.webp" },
  { id: "88", name: "Angel Hair", category: "Grains", image: "/ingredients/angel-hair.webp" },
  { id: "27", name: "Avocado", category: "Fruits", image: "/ingredients/avocado.webp" },
  { id: "11", name: "Bananas", category: "Fruits", image: "/ingredients/banana.webp" },
  { id: "78", name: "Basil", category: "Aromatics", image: "/ingredients/basil.webp" },
  { id: "89", name: "Bean Sprouts", category: "Vegetables", image: "/ingredients/bean-sprouts.webp" },
  { id: "65", name: "Beef Stock", category: "Pantry", image: "/ingredients/beef-stock.webp" },
  { id: "42", name: "Beef Top Round", category: "Proteins", image: "/ingredients/top-round.webp" },
  { id: "22", name: "Beer", category: "Pantry", image: "/ingredients/beer.webp" },
  { id: "28", name: "Bell Pepper", category: "Vegetables", image: "/ingredients/bell-pepper.webp" },
  { id: "44", name: "Bell Pepper Red", category: "Vegetables", image: "/ingredients/bell-pepper-red.webp" },
  { id: "43", name: "Bread Crumbs", category: "Grains", image: "/ingredients/breadcrumbs.webp" },
  { id: "60", name: "Brown Rice", category: "Grains", image: "/ingredients/brown-rice.webp" },
  { id: "49", name: "Butter", category: "Dairy", image: "/ingredients/butter.webp" },
  { id: "2", name: "Carrot", category: "Vegetables", image: "/ingredients/carrot.webp" },
  { id: "66", name: "Cassava", category: "Vegetables", image: "/ingredients/cassava.webp" },
  { id: "73", name: "Cecina", category: "Proteins", image: "/ingredients/cecina.webp" },
  { id: "6", name: "Celery", category: "Vegetables", image: "/ingredients/cellery.webp" },
  { id: "29", name: "Chicken Breast", category: "Proteins", image: "/ingredients/chicken-breast.webp" },
  { id: "61", name: "Chicken Leg Quarter", category: "Proteins", image: "/ingredients/chicken-leg-quarter.webp" },
  { id: "50", name: "Chicken Stock", category: "Pantry", image: "/ingredients/chicken-stock.webp" },
  { id: "74", name: "Chicken Thigh", category: "Proteins", image: "/ingredients/chicken-thigh.webp" },
  { id: "62", name: "Chicken Wings", category: "Proteins", image: "/ingredients/chicken-wings.webp" },
  { id: "14", name: "Chili Crisp", category: "Pantry", image: "/ingredients/chili-crisp.webp" },
  { id: "90", name: "Chocolate Bar", category: "Pantry", image: "/ingredients/chocolate-bar.webp" },
  { id: "79", name: "Chorizo", category: "Proteins", image: "/ingredients/chorizo.webp" },
  { id: "20", name: "Cilantro", category: "Aromatics", image: "/ingredients/cilantro.webp" },
  { id: "91", name: "Cinnamon", category: "Pantry", image: "/ingredients/cinnamon.webp" },
  { id: "80", name: "Coffee Beans", category: "Pantry", image: "/ingredients/coffee-beans.webp" },
  { id: "58", name: "Corn", category: "Vegetables", image: "/ingredients/corn.webp" },
  { id: "67", name: "Edamame", category: "Vegetables", image: "/ingredients/edamame.webp" },
  { id: "30", name: "Eggs", category: "Proteins", image: "/ingredients/eggs.webp" },
  { id: "45", name: "Feta Cheese", category: "Dairy", image: "/ingredients/feta-cheese.webp" },
  { id: "68", name: "Flour", category: "Grains", image: "/ingredients/flour.webp" },
  { id: "18", name: "Garlic", category: "Aromatics", image: "/ingredients/garlic.webp" },
  { id: "8", name: "Ginger", category: "Aromatics", image: "/ingredients/ginger.webp" },
  { id: "15", name: "Golden Curry", category: "Pantry", image: "/ingredients/golden-curry.webp" },
  { id: "5", name: "Grapes", category: "Fruits", image: "/ingredients/grapes.webp" },
  { id: "69", name: "Greek Yogurt", category: "Dairy", image: "/ingredients/greek-yogurt.webp" },
  { id: "31", name: "Green Apple", category: "Fruits", image: "/ingredients/green-apple.webp" },
  { id: "99", name: "Ground Beef", category: "Proteins", image: "/ingredients/ground-beef.webp" },
  { id: "81", name: "Hoisin Sauce", category: "Pantry", image: "/ingredients/hoisin-sauce.webp" },
  { id: "51", name: "Honey", category: "Pantry", image: "/ingredients/honey.webp" },
  { id: "46", name: "Jalapeño", category: "Aromatics", image: "/ingredients/jalapeno.webp" },
  { id: "63", name: "Lemon", category: "Fruits", image: "/ingredients/lemon.webp" },
  { id: "82", name: "Lentils", category: "Grains", image: "/ingredients/lentils.webp" },
  { id: "32", name: "Lettuce", category: "Vegetables", image: "/ingredients/lettuce.webp" },
  { id: "7", name: "Limes", category: "Fruits", image: "/ingredients/limes.webp" },
  { id: "75", name: "Lucuma", category: "Fruits", image: "/ingredients/lucuma.webp" },
  { id: "33", name: "Mayo", category: "Pantry", image: "/ingredients/mayo.webp" },
  { id: "92", name: "Mint", category: "Aromatics", image: "/ingredients/mint.webp" },
  { id: "76", name: "Mozzarella Cheese", category: "Dairy", image: "/ingredients/mozzarella-cheese.webp" },
  { id: "24", name: "Mustard", category: "Pantry", image: "/ingredients/mustard.webp" },
  { id: "55", name: "NY Strip Steak", category: "Proteins", image: "/ingredients/ntc-steak.webp" },
  { id: "83", name: "Oats", category: "Grains", image: "/ingredients/oats.webp" },
  { id: "34", name: "Oil", category: "Pantry", image: "/ingredients/oil.webp" },
  { id: "64", name: "Orange", category: "Fruits", image: "/ingredients/orange.webp" },
  { id: "35", name: "Oyster Sauce", category: "Pantry", image: "/ingredients/oyster-sauce.webp" },
  { id: "77", name: "Parmesan Cheese", category: "Dairy", image: "/ingredients/parmesan-cheese.webp" },
  { id: "25", name: "Parsley", category: "Aromatics", image: "/ingredients/parsley.webp" },
  { id: "84", name: "Passion Fruit", category: "Fruits", image: "/ingredients/passion-fruit.webp" },
  { id: "36", name: "Pineapple", category: "Fruits", image: "/ingredients/pineapple.webp" },
  { id: "1", name: "Potato", category: "Vegetables", image: "/ingredients/potato.webp" },
  { id: "70", name: "Queso Fresco", category: "Dairy", image: "/ingredients/queso-fresco.webp" },
  { id: "85", name: "Ravioli", category: "Grains", image: "/ingredients/ravioli.webp" },
  { id: "37", name: "Red Apple", category: "Fruits", image: "/ingredients/red-apple.webp" },
  { id: "10", name: "Red Onion", category: "Aromatics", image: "/ingredients/red-onion.webp" },
  { id: "26", name: "Red Wine Vinegar", category: "Pantry", image: "/ingredients/red-wine-vinegar.webp" },
  { id: "93", name: "Ribeye", category: "Proteins", image: "/ingredients/ribeye.webp" },
  { id: "13", name: "Rice", category: "Grains", image: "/ingredients/rice.webp" },
  { id: "86", name: "Rocoto", category: "Aromatics", image: "/ingredients/rocoto.webp" },
  { id: "94", name: "Rosemary", category: "Aromatics", image: "/ingredients/rosemary.webp" },
  { id: "56", name: "Sake", category: "Pantry", image: "/ingredients/sake.webp" },
  { id: "95", name: "Salmon", category: "Proteins", image: "/ingredients/salmon-fish.webp" },
  { id: "47", name: "San Marzano Tomatoes", category: "Pantry", image: "/ingredients/san-marzano-tomatoes.webp" },
  { id: "57", name: "Scallion", category: "Aromatics", image: "/ingredients/scallion.webp" },
  { id: "96", name: "Seaweed", category: "Vegetables", image: "/ingredients/seaweed.webp" },
  { id: "19", name: "Short Ribs", category: "Proteins", image: "/ingredients/short-ribs.webp" },
  { id: "97", name: "Shrimp", category: "Proteins", image: "/ingredients/shrimp.webp" },
  { id: "100", name: "Sirloin Steak", category: "Proteins", image: "/ingredients/sirloin-steak.webp" },
  { id: "3", name: "Soy Sauce", category: "Pantry", image: "/ingredients/soy-sauce.webp" },
  { id: "21", name: "Squash", category: "Vegetables", image: "/ingredients/squash.webp" },
  { id: "38", name: "Sriracha Sauce", category: "Pantry", image: "/ingredients/sriracha-sauce.webp" },
  { id: "12", name: "Strawberries", category: "Fruits", image: "/ingredients/strawberries.webp" },
  { id: "4", name: "Sweet Potato", category: "Vegetables", image: "/ingredients/sweet-potato.webp" },
  { id: "71", name: "Thin Sliced Chicken Breast", category: "Proteins", image: "/ingredients/thin-sliced-chicken-breast.webp" },
  { id: "39", name: "Tomato", category: "Vegetables", image: "/ingredients/tomato.webp" },
  { id: "52", name: "Tomato Paste", category: "Pantry", image: "/ingredients/tomato-paste.webp" },
  { id: "98", name: "Tuna", category: "Proteins", image: "/ingredients/tuna-fish.webp" },
  { id: "48", name: "Veggie Stock", category: "Pantry", image: "/ingredients/veggie-stock.webp" },
  { id: "87", name: "White Fish", category: "Proteins", image: "/ingredients/white-fish.webp" },
  { id: "40", name: "White Vinegar", category: "Pantry", image: "/ingredients/white-vinegar.webp" },
  { id: "23", name: "Whole Chicken", category: "Proteins", image: "/ingredients/whole-chicken.webp" },
  { id: "72", name: "Whole Milk", category: "Dairy", image: "/ingredients/whole-milk.webp" },
  { id: "53", name: "Worcestershire Sauce", category: "Pantry", image: "/ingredients/worcestershire-sauce.webp" },
  { id: "41", name: "Yellow Onion", category: "Aromatics", image: "/ingredients/yellow-onion.webp" },
];

export const categories = [
  "All",
  "Fruits",
  "Vegetables",
  "Aromatics",
  "Proteins",
  "Dairy",
  "Grains",
  "Pantry",
];
